Add -fgnu89-inline to CFLAGS
In GCC 5.1 default C standard changed to -std=gnu11. This changed behavior of
inline functions. Build error is:
[  342s] CMakeFiles/starter.dir/src/hw_key.c.o: In function `_launch_by_home_key':
[  342s] /home/abuild/rpmbuild/BUILD/starter-0.4.62/src/hw_key.c:101: undefined reference to `menu_daemon_open_homescreen'
[  342s] /home/abuild/rpmbuild/BUILD/starter-0.4.62/src/hw_key.c:101: error: undefined reference to 'menu_daemon_open_homescreen'
[  342s] collect2: error: ld returned 1 exit status

Changing back to gnu89 inlining mode fixes the issue.

Change-Id: Iebc984868b700ff735a739eda9af57319e5710ee
Signed-off-by: Yury Usishchev <y.usishchev@samsung.com>